"""Initial Migration2

Revision ID: 4814947c9016
Revises: 
Create Date: 2018-09-06 10:28:04.527228

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '4814947c9016'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('pitchroles',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('pitchusers',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('username', sa.String(length=255), nullable=True),
    sa.Column('email', sa.String(length=255), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_pitchusers_email'), 'pitchusers', ['email'], unique=True)
    op.create_index(op.f('ix_pitchusers_username'), 'pitchusers', ['username'], unique=False)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_pitchusers_username'), table_name='pitchusers')
    op.drop_index(op.f('ix_pitchusers_email'), table_name='pitchusers')
    op.drop_table('pitchusers')
    op.drop_table('pitchroles')
    # ### end Alembic commands ###
