"""forms for picomments added

Revision ID: 943272cee971
Revises: 
Create Date: 2018-09-11 10:59:25.143484

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '943272cee971'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('pitches', sa.Column('comments', sa.String(length=255), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('pitches', 'comments')
    # ### end Alembic commands ###
