"""db with pass_secure

Revision ID: dc6dbda27bef
Revises: 4814947c9016
Create Date: 2018-09-08 12:38:51.641975

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'dc6dbda27bef'
down_revision = '4814947c9016'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('pitchroles')
    op.add_column('pitchusers', sa.Column('pass_secure', sa.String(length=255), nullable=True))
    op.add_column('pitchusers', sa.Column('password_hash', sa.String(length=255), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('pitchusers', 'password_hash')
    op.drop_column('pitchusers', 'pass_secure')
    op.create_table('pitchroles',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('name', sa.VARCHAR(length=255), autoincrement=False, nullable=True),
    sa.PrimaryKeyConstraint('id', name='pitchroles_pkey')
    )
    # ### end Alembic commands ###
